# Generated by Django 4.1.1 on 2022-10-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('day', models.CharField(max_length=150)),
                ('start_time', models.CharField(max_length=150)),
                ('end_time', models.CharField(max_length=150)),
                ('start_day', models.CharField(max_length=150)),
                ('end_day', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=150)),
            ],
        ),
    ]
