# Generated by Django 4.1.1 on 2022-10-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%D'),
        ),
    ]
