# Generated by Django 4.1.1 on 2022-10-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
